# Generated by Django 5.0.7 on 2025-07-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
